spring:
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

server:
  port: 8081

socket:
  server:
    port: 9999
    threadPool: 200

balancer:
  rest:
    search:
      url: /balancer-api/search/files

build:
    version: @project.version@

